### ISSUE TITLE
Are values meant to display in lux?

### ISSUE THREAD

**Issue by ssuess** [dblommesteijn/homebridge-p1-monitor#1]
**Describe Your Problem:**
Hi and thanks so much for this plugin. It installs and clearly connects to my p1monitor api, but the values the homebridge accessories page are showing are in LUX? Is this expected?

**Logs:**
There were no logs found at all, completely blank

**Plugin Config:**

```json
{
    "ipAddress": "192.168.10.77",
    "showPhases": true,
    "showGas": true,
    "platform": "HomebridgeP1Monitor"
}
```

**Screenshots:**
![lux](https://github.com/dblommesteijn/homebridge-p1-monitor/assets/288542/d42475fe-e104-47c3-9c0d-8fcab29148f5)

**Environment:**

* **Plugin Version**: 0.0.3
* **Homebridge Version**: 1.82
* **Node.js Version**: v20.9.0
* **NPM Version**: 10.8.1
* **Operating System**: Mac OS sonoma

Thanks!

**Comment by dblommesteijn** [comment]
Hi, thanks for your inquiry. Apple Homekit does not support any kind of energy metrics, the closest I could find are lux, they are pretty stable accessories and offer a wide range of values. 
Hope this helps.

**Comment by ssuess** [comment]
Understood, thanks for the reply!
